"""Connected App (OAuth2 client_credentials) example for DocuWare.

This script demonstrates how to connect to DocuWare using a Connected App
(server-to-server integration) with the client_credentials grant type.
No interactive user login is needed — the app authenticates directly with
its client ID and secret.

PREREQUISITES — DocuWare Connected App Registration
====================================================

Before running this script, a Connected App must be registered in DocuWare:

  DocuWare Configuration → Integrations → Connected Apps → Add

Settings:
  App type:     Confidential application
  Grant type:   Client Credentials
  Client ID:    a UUID assigned by DocuWare when you create the registration
                (copy it — you will need it below)
  Client Secret: generated by DocuWare (copy it — you will need it below)

  Scopes:
    docuware.platform  (default, sufficient for most use cases)

  IMPORTANT: The Connected App must be assigned to the organization(s) and
  user(s) it should act on behalf of.  Without this assignment, the token
  request will fail with HTTP 400.

HOW IT WORKS
============

1. The script discovers the token endpoint automatically from the DocuWare
   instance (via IdentityServiceInfo + OpenID Connect discovery).
2. It requests an access token using the client_credentials grant.
3. The access token is used as a Bearer token for all subsequent API calls.
4. On 401/403, the library automatically obtains a fresh token.

Usage:
    python connected_app.py

You can also set environment variables instead of entering values interactively:

    export DW_URL=https://acme.docuware.cloud/DocuWare/Platform
    export DW_CLIENT_ID=your-client-id
    export DW_CLIENT_SECRET=your-client-secret
    python connected_app.py
"""

from __future__ import annotations

import logging
import os
import sys

import docuware

# Optional: enable debug logging to see the token exchange
# logging.basicConfig(level=logging.DEBUG, stream=sys.stderr)
# logging.getLogger("httpx").setLevel(logging.WARNING)
# logging.getLogger("httpcore").setLevel(logging.WARNING)


def main() -> None:
    print()
    print("DocuWare Connected App (client_credentials) — Example")
    print("=" * 55)
    print()

    # --- Collect inputs (env vars or interactive) ---
    url = os.environ.get("DW_URL", "").strip()
    if not url:
        url = input("DocuWare URL or hostname (e.g. acme.docuware.cloud): ").strip()
    if not url:
        print("Error: URL is required.")
        return
    if "/DocuWare/" not in url:
        if not url.startswith("http"):
            url = "https://" + url
        url = url.rstrip("/") + "/DocuWare/Platform"
    print(f"  → {url}")
    print()

    client_id = os.environ.get("DW_CLIENT_ID", "").strip()
    if not client_id:
        client_id = input("Client ID (from Connected App): ").strip()
    if not client_id:
        print("Error: Client ID is required.")
        return

    client_secret = os.environ.get("DW_CLIENT_SECRET", "").strip()
    if not client_secret:
        client_secret = input("Client Secret (from Connected App): ").strip()
    if not client_secret:
        print("Error: Client Secret is required.")
        return
    print()

    # --- Connect ---
    print("Connecting to DocuWare via Connected App...")
    try:
        client = docuware.connect_with_connected_app(
            url=url,
            client_id=client_id,
            client_secret=client_secret,
            # scope="docuware.platform",        # default, usually sufficient
            # verify_certificate=True,           # set to False for self-signed certs
        )
    except docuware.AccountError as exc:
        print(f"Authentication failed: {exc}")
        print()
        print("Common causes:")
        print("  - Invalid client_id or client_secret")
        print("  - Connected App not assigned to an organization/user")
        print("  - Wrong scope requested")
        return
    except Exception as exc:
        print(f"Connection failed: {exc}")
        return

    print(f"Connected to {client.conn.base_url}")
    print()

    # --- List organizations and file cabinets ---
    print("Organizations and file cabinets:")
    for org in client.organizations:
        print(f"  Organization: {org.name} ({org.id})")
        for fc in org.file_cabinets:
            print(f"    - {fc.name} ({fc.id})")
    print()

    # --- Reusable snippet ---
    print("Reusable snippet for your own code:")
    print()
    print("  import docuware")
    print()
    print("  client = docuware.connect_with_connected_app(")
    print(f"      url={url!r},")
    print("      client_id='your-client-id',")
    print("      client_secret='your-client-secret',")
    print("  )")
    print()
    print("  # The client automatically handles token refresh on 401/403.")
    print("  for org in client.organizations:")
    print("      for fc in org.file_cabinets:")
    print("          print(fc.name)")
    print()


if __name__ == "__main__":
    main()
